//hosting
var a;
console.log(a); //undefined
var a = 10;
console.log(a); //10

//HOSTING DOES NOT PHYSICALLY MOVE YOUR CODE.
//IT IS A MENTAL MODEL TO UNDERSTAND HOW THE JAVASCRIPT ENGINE WORKS.
//JS ENGINE HANDLES DECLARATIONS DURING COMPLIATION PHASE AND ASSIGNS THEM TO MEMORY.
